{
    "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
    "name": "Org Markup",
    "patterns": [
        {
            "name": "comment.line.double-dash.org",
            "match": "^\\s*[*]{1} [^\\[\\]:\\n]*"
        },
        {
            "name": "keyword.control.org",
            "match": "^\\s*[*]{2} [^\\[\\]:\\n]*"
        },
        {
            "name": "comment.line.double-dash.org",
            "match": "comment.line.double-dash.org"
        },
        {
            "name": "comment.line.double-slash.org",
            "match": "comment.line.double-slash.org"
        },
        {
            "name": "comment.line.number-sign.org",
            "match": "comment.line.number-sign.org"
        },
        {
            "name": "comment.line.percentage.org",
            "match": "comment.line.percentage.org"
        },
        {
            "name": "comment.block.documentation.org",
            "match": "comment.block.documentation.org"
        },
        {
            "name": "comment.line.percentage.org",
            "match": "comment.line.percentage.org"
        },
        {
            "name": "constant.numeric.org",
            "match": "constant.numeric.org"
        },
        {
            "name": "constant.character.org",
            "match": "constant.character.org"
        },
        {
            "name": "constant.character.escape.org",
            "match": "constant.character.escape.org"
        },
        {
            "name": "constant.language.org",
            "match": "constant.language.org"
        },
        {
            "name": "constant.other.org",
            "match": "constant.other.org"
        },
        {
            "name": "entity.name.function.org",
            "match": "entity.name.function.org"
        },
        {
            "name": "entity.name.type.org",
            "match": "entity.name.type.org"
        },
        {
            "name": "entity.name.tag.org",
            "match": "entity.name.tag.org"
        },
        {
            "name": "entity.name.section.org",
            "match": "entity.name.section.org"
        },
        {
            "name": "entity.other.inherited-class.org",
            "match": "entity.other.inherited-class.org"
        },
        {
            "name": "entity.other.attribute-name.org",
            "match": "entity.other.attribute-name.org"
        },
        {
            "name": "invalid.illegal.org",
            "match": "invalid.illegal.org"
        },
        {
            "name": "invalid.deprecated.org",
            "match": "invalid.deprecated.org"
        },
        {
            "name": "keyword.control.org",
            "match": "keyword.control.org"
        },
        {
            "name": "keyword.operator.org",
            "match": "keyword.operator.org"
        },
        {
            "name": "keyword.other.org",
            "match": "keyword.other.org"
        },
        {
            "name": "markup.underline.org",
            "match": "markup.underline.org"
        },
        {
            "name": "markup.underline.link.org",
            "match": "markup.underline.link.org"
        },
        {
            "name": "markup.heading.org",
            "match": "markup.heading.org"
        },
        {
            "name": "markup.heading.1.org",
            "match": "markup.heading.1.org"
        },
        {
            "name": "markup.heading.2.org",
            "match": "markup.heading.2.org"
        },
        {
            "name": "markup.heading.3.org",
            "match": "markup.heading.3.org"
        },
        {
            "name": "markup.heading.4.org",
            "match": "markup.heading.4.org"
        },
        {
            "name": "markup.heading.5.org",
            "match": "markup.heading.5.org"
        },
        {
            "name": "markup.heading.6.org",
            "match": "markup.heading.6.org"
        },
        {
            "name": "markup.bold.org",
            "match": "markup.bold.org"
        },
        {
            "name": "markup.italic.org",
            "match": "markup.italic.org"
        },
        {
            "name": "markup.list.org",
            "match": "markup.list.org"
        },
        {
            "name": "markup.quote.org",
            "match": "markup.quote.org"
        },
        {
            "name": "markup.raw.org",
            "match": "markup.raw.org"
        },
        {
            "name": "markup.other.org",
            "match": "markup.other.org"
        },
        {
            "name": "storage.type.org",
            "match": "storage.type.org"
        },
        {
            "name": "storage.modifier.org",
            "match": "storage.modifier.org"
        },
        {
            "name": "string.quoted.org",
            "match": "string.quoted.org"
        },
        {
            "name": "string.quoted.single.org",
            "match": "string.quoted.single.org"
        },
        {
            "name": "string.quoted.double.org",
            "match": "string.quoted.double.org"
        },
        {
            "name": "string.quoted.triple.org",
            "match": "string.quoted.triple.org"
        },
        {
            "name": "string.quoted.other.org",
            "match": "string.quoted.other.org"
        },
        {
            "name": "string.unquoted.org",
            "match": "string.unquoted.org"
        },
        {
            "name": "string.interpolated.org",
            "match": "string.interpolated.org"
        },
        {
            "name": "string.regexp.org",
            "match": "string.regexp.org"
        },
        {
            "name": "string.other.org",
            "match": "string.other.org"
        },
        {
            "name": "support.function.org",
            "match": "support.function.org"
        },
        {
            "name": "support.class.org",
            "match": "support.class.org"
        },
        {
            "name": "support.type.org",
            "match": "support.type.org"
        },
        {
            "name": "support.variable.org",
            "match": "support.variable.org"
        },
        {
            "name": "support.constant.org",
            "match": "support.constant.org"
        },
        {
            "name": "support.other.org",
            "match": "support.other.org"
        },
        {
            "name": "variable.parameter.org",
            "match": "variable.parameter.org"
        },
        {
            "name": "variable.language.org",
            "match": "variable.language.org"
        },
        {
            "name": "variable.other.org",
            "match": "variable.other.org"
        },
        {
            "include": "#keywords"
        },
        {
            "include": "#strings"
        }
    ],
    "repository": {
        "keywords": {
            "patterns": [
                {
                    "name": "keyword.control.org",
                    "match": "\\b(if|while|for|return)\\b"
                }
            ]
        },
        "strings": {
            "name": "string.quoted.double.org",
            "begin": "\"",
            "end": "\"",
            "patterns": [
                {
                    "name": "constant.character.escape.org",
                    "match": "\\\\."
                }
            ]
        }
    },
    "scopeName": "source.org"
}